import type { Store } from "./types";

export const GENRE_COLORS: Record<string, string> = {
  居酒屋: "#c4554d",
  ラーメン: "#d97706",
  カフェ: "#7c6f64",
  ベーカリー: "#b87333",
  焼肉: "#8b1e1e",
  カレー: "#c97b2a",
  タイ料理: "#6a7f3a",
  寿司: "#143d5c",
  スイーツ: "#c2528b",
  イタリアン: "#2d5f3f",
  中華: "#9b2226",
  フレンチ: "#3a5a82",
  沖縄料理: "#c95d4a",
  和菓子: "#6b4226",
  そば: "#4a5c3a",
};

export const MOCK_STORES: Store[] = [
  { name:"炭火焼鳥 とりまさ 赤羽店", addr:"東京都北区赤羽1-22-8 ミヤビルB1", pref:"東京都", city:"北区", date:"2026-04-22", openDate:"2026-04-25", genre:"居酒屋", tel:"03-1234-5678", thumb:"", sources:[{name:"赤羽マガジン", url:"https://akabane-shinbun.com/", type:"独立系ブログ"},{name:"号外NET 北区", url:"https://tokyokita.goguynet.jp/", type:"号外NET"}] },
  { name:"パン工房 Boulangerie MIE", addr:"東京都板橋区常盤台2-5-1", pref:"東京都", city:"板橋区", date:"2026-04-22", openDate:"2026-04-28", genre:"ベーカリー", tel:"", thumb:"", sources:[{name:"いたばしTIMES", url:"https://itabashi-times.com/", type:"独立系ブログ"}] },
  { name:"中華そば 四ツ木製麺所", addr:"東京都葛飾区四つ木3-12-4", pref:"東京都", city:"葛飾区", date:"2026-04-21", openDate:"", genre:"ラーメン", tel:"03-6666-7777", thumb:"", sources:[{name:"葛飾つうしん", url:"https://katsushika-tsushin.com/", type:"独立系ブログ"},{name:"号外NET 葛飾区", url:"https://katsushika.goguynet.jp/", type:"号外NET"}] },
  { name:"Cafe & Bakery TSUBAME", addr:"東京都豊島区池袋2-40-13 グランドビル1F", pref:"東京都", city:"豊島区", date:"2026-04-21", openDate:"2026-04-20", genre:"カフェ", tel:"03-9876-5432", thumb:"", sources:[{name:"池袋タイムズ", url:"https://ikebukuro-times.com/", type:"独立系ブログ"}] },
  { name:"やきとん もつ寅", addr:"東京都大田区蒲田5-15-8", pref:"東京都", city:"大田区", date:"2026-04-20", openDate:"", genre:"居酒屋", tel:"", thumb:"", sources:[{name:"大田区タイムズ", url:"https://otaku-times.com/", type:"独立系ブログ"},{name:"おおたく通信", url:"https://ootaku2shin.com/", type:"独立系ブログ"}] },
  { name:"スープカレー SAMA 立川店", addr:"東京都立川市曙町2-11-2", pref:"東京都", city:"立川市", date:"2026-04-20", openDate:"2026-05-01", genre:"カレー", tel:"042-555-1234", thumb:"", sources:[{name:"いいね！立川", url:"https://iine-tachikawa.net/", type:"独立系ブログ"}] },
  { name:"焼肉ホルモン にくまる 多摩センター店", addr:"東京都多摩市落合1-46-1", pref:"東京都", city:"多摩市", date:"2026-04-19", openDate:"2026-04-19", genre:"焼肉", tel:"042-333-7788", thumb:"", sources:[{name:"多摩ポン", url:"https://tamapon.com/", type:"独立系ブログ"}] },
  { name:"タイ料理 Baan Esan", addr:"東京都八王子市旭町9-1", pref:"東京都", city:"八王子市", date:"2026-04-18", openDate:"", genre:"タイ料理", tel:"", thumb:"", sources:[{name:"八王子ジャーニー", url:"https://8dabe.com/", type:"独立系ブログ"}] },
  { name:"寿司 銀座 久兵衛 横浜高島屋店", addr:"神奈川県横浜市西区南幸1-6-31", pref:"神奈川県", city:"横浜市西区", date:"2026-04-22", openDate:"2026-04-26", genre:"寿司", tel:"045-321-1111", thumb:"", sources:[{name:"号外NET 横浜中区・西区", url:"https://yokohamanaka-nishi.goguynet.jp/", type:"号外NET"},{name:"ヨコハマ経済新聞", url:"https://www.hamakei.com/", type:"経済新聞"}] },
  { name:"川崎プリンホテル", addr:"神奈川県川崎市中原区小杉町3-13", pref:"神奈川県", city:"川崎市中原区", date:"2026-04-22", openDate:"2026-05-10", genre:"スイーツ", tel:"", thumb:"", sources:[{name:"かなレポ川崎", url:"https://kanagawa-report.com/", type:"独立系ブログ"},{name:"号外NET 川崎市中原区", url:"https://kawasakinakahara.goguynet.jp/", type:"号外NET"},{name:"川崎経済新聞", url:"https://kawasaki.keizai.biz/", type:"経済新聞"}] },
  { name:"イタリアン Osteria da SAKU", addr:"神奈川県藤沢市鵠沼石上1-3-10", pref:"神奈川県", city:"藤沢市", date:"2026-04-21", openDate:"2026-04-18", genre:"イタリアン", tel:"0466-12-3456", thumb:"", sources:[{name:"湘南人", url:"https://shonanjin.com/", type:"独立系ブログ"},{name:"JIMOHACK湘南", url:"https://jimohack-shonan.jp/", type:"独立系ブログ"}] },
  { name:"串カツ田中 大和駅前店", addr:"神奈川県大和市大和東1-1-1", pref:"神奈川県", city:"大和市", date:"2026-04-19", openDate:"", genre:"居酒屋", tel:"046-111-2222", thumb:"", sources:[{name:"大和とぴっく", url:"https://www.yamatopi.jp/", type:"独立系ブログ"}] },
  { name:"町中華 福来軒 相模原店", addr:"神奈川県相模原市中央区矢部3-22-1", pref:"神奈川県", city:"相模原市中央区", date:"2026-04-18", openDate:"2026-04-15", genre:"中華", tel:"", thumb:"", sources:[{name:"さがみはらあたり。", url:"https://sagamiharaatari.com/", type:"独立系ブログ"}] },
  { name:"船橋ビストロ La Table", addr:"千葉県船橋市本町4-38-20", pref:"千葉県", city:"船橋市", date:"2026-04-22", openDate:"2026-05-03", genre:"フレンチ", tel:"047-123-4567", thumb:"", sources:[{name:"船橋つうしん", url:"https://funabashi-tsushin.com/", type:"独立系ブログ"},{name:"号外NET 船橋市", url:"https://funabashi.goguynet.jp/", type:"号外NET"},{name:"船橋経済新聞", url:"https://funabashi.keizai.biz/", type:"経済新聞"}] },
  { name:"海鮮居酒屋 魚々 松戸店", addr:"千葉県松戸市本町1-15", pref:"千葉県", city:"松戸市", date:"2026-04-21", openDate:"", genre:"居酒屋", tel:"", thumb:"", sources:[{name:"松戸つうしん", url:"https://matsudo-tsushin.com/", type:"独立系ブログ"}] },
  { name:"ドッグカフェ WAN-WAN", addr:"千葉県柏市柏1-1-11", pref:"千葉県", city:"柏市", date:"2026-04-20", openDate:"2026-04-24", genre:"カフェ", tel:"04-7100-0000", thumb:"", sources:[{name:"柏つうしん", url:"https://kashiwa-tsushin.com/", type:"独立系ブログ"},{name:"まちっと柏", url:"https://machitto.jp/kashiwa/", type:"独立系ブログ"}] },
  { name:"沖縄料理 ちゅらさん", addr:"千葉県市川市八幡3-4-1", pref:"千葉県", city:"市川市", date:"2026-04-19", openDate:"2026-04-19", genre:"沖縄料理", tel:"", thumb:"", sources:[{name:"市川にゅ～す", url:"https://ichi-24.jp/", type:"独立系ブログ"}] },
  { name:"中華食堂 ちゃんぽん亭 越谷店", addr:"埼玉県越谷市南越谷1-11-4", pref:"埼玉県", city:"越谷市", date:"2026-04-22", openDate:"2026-04-27", genre:"中華", tel:"048-123-9999", thumb:"", sources:[{name:"越谷雑談がやてっく", url:"https://koshigaya.gayatec.jp/", type:"独立系ブログ"},{name:"号外NET 越谷市", url:"https://koshigaya.goguynet.jp/", type:"号外NET"}] },
  { name:"韓国カフェ OPPA COFFEE", addr:"埼玉県川口市本町4-3-6", pref:"埼玉県", city:"川口市", date:"2026-04-21", openDate:"", genre:"カフェ", tel:"", thumb:"", sources:[{name:"川口マガジン", url:"https://kawaguchi-magazine.com/", type:"独立系ブログ"},{name:"号外NET 川口市", url:"https://kawaguchi.goguynet.jp/", type:"号外NET"}] },
  { name:"餃子酒場 GYOZA HOUSE", addr:"埼玉県さいたま市大宮区桜木町2-1-1", pref:"埼玉県", city:"さいたま市大宮区", date:"2026-04-20", openDate:"2026-04-30", genre:"居酒屋", tel:"048-777-8888", thumb:"", sources:[{name:"宮原大宮ドットコム", url:"https://miyahara-kitaku.com/", type:"独立系ブログ"},{name:"大宮経済新聞", url:"https://omiya.keizai.biz/", type:"経済新聞"}] },
  { name:"和菓子 三郷庵", addr:"埼玉県三郷市中央1-1-1", pref:"埼玉県", city:"三郷市", date:"2026-04-19", openDate:"2026-04-21", genre:"和菓子", tel:"048-999-0000", thumb:"", sources:[{name:"三郷ぐらし", url:"https://misato-gurashi.com/", type:"独立系ブログ"}] },
  { name:"手打ちそば 所沢庵", addr:"埼玉県所沢市日吉町4-13", pref:"埼玉県", city:"所沢市", date:"2026-04-17", openDate:"", genre:"そば", tel:"", thumb:"", sources:[{name:"所沢なび", url:"https://tokorozawanavi.com/", type:"独立系ブログ"}] },
];
